version: "3"

services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    networks:
      - dremio-spark
    ports:
      - 19120:19120
    volumes:
      - nessie-data:/var/lib/nessie

  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - dremio-spark
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio-data:/data

  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      - dremio-spark
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    volumes:
      - dremio-data:/opt/dremio/data

  # Spark
  spark:
    platform: linux/x86_64
    image: alexmerced/spark35notebook:latest
    container_name: spark
    networks:
      - dremio-spark
    ports: 
      - 8080:8080  # Master Web UI
      - 7077:7077  # Master Port
      - 8888:8888  # Notebook
